// Auto-generated by scripts/generate-sticker-manifest.js. Do not edit manually.
export type StickerAsset = { id: string; label: string; source: any };
export const STICKERS: StickerAsset[] = [
  { id: 'heart', label: 'Heart', source: require('../../assets/stickers/heart.png') },
  { id: 'laugh', label: 'Laugh', source: require('../../assets/stickers/laugh.png') },
  { id: 'party', label: 'Party', source: require('../../assets/stickers/party.png') },
  { id: 'star', label: 'Star', source: require('../../assets/stickers/star.png') },
  { id: 'thumbs-up', label: 'Thumbs Up', source: require('../../assets/stickers/thumbs-up.png') },
];
